spring.application.name=backend


logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Konfiguracja bazy danych PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/biletmiejski
spring.datasource.username=biletuser
spring.datasource.password=biletpass

# Wy??cz domy?ln? inicjalizacj? Springa
spring.jpa.hibernate.ddl-auto=none

# Aktywuj Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
# Reset danych przy kazdym uruchomieniu
spring.liquibase.drop-first=true

# Konfiguracja JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# port serwera
server.port=8080

# pretty JSON
spring.jackson.serialization.indent_output=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
