spring.application.name=backend

# Logowanie
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Konfiguracja bazy danych PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/biletmiejski
spring.datasource.username=biletuser
spring.datasource.password=biletpass

# Konfiguracja JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# port serwera
server.port=8080

# pretty JSON
spring.jackson.serialization.indent_output=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs